# Generated by Django 3.1.7 on 2021-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('genreName', models.CharField(max_length=16, verbose_name='genre_name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genre',
                'db_table': 'genre',
            },
        ),
    ]
