# Generated by Django 3.1.7 on 2021-04-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=16, verbose_name='genre_name')),
                ('movieName', models.CharField(max_length=16, verbose_name='genre_name')),
                ('year', models.CharField(max_length=16, verbose_name='genre_name')),
                ('director', models.CharField(max_length=16, verbose_name='genre_name')),
                ('actor', models.CharField(max_length=128, verbose_name='genre_name')),
                ('plot', models.CharField(max_length=512, verbose_name='genre_name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie',
                'db_table': 'movie',
            },
        ),
    ]
