# Generated by Django 3.1.7 on 2021-04-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210406_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
                ('genreId', models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, to='customer.genre', verbose_name='genre_id')),
                ('movieId', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='customer.movie', verbose_name='movie_id')),
            ],
            options={
                'verbose_name': 'Movie_Genre',
                'verbose_name_plural': 'Movie_Genre',
                'db_table': 'movie_genre',
            },
        ),
    ]
