# Generated by Django 3.1.7 on 2021-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(default='', max_length=16, primary_key=True, serialize=False, verbose_name='genre_id')),
                ('genre_name', models.CharField(default='', max_length=32, verbose_name='genre_name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genre',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='movie_id')),
                ('title', models.CharField(default='', max_length=128, verbose_name='movie_title')),
                ('imdb_id', models.CharField(default='', max_length=16, verbose_name='imdb_id')),
                ('release_date', models.CharField(default='', max_length=16, verbose_name='release_date')),
                ('vote_average', models.CharField(default='', max_length=8, verbose_name='vote_average')),
                ('overview', models.CharField(default='', max_length=1024, verbose_name='overview')),
                ('poster_url', models.CharField(default='', max_length=256, verbose_name='poster_url')),
                ('director', models.CharField(default='', max_length=64, verbose_name='director')),
                ('main_actor', models.CharField(default='', max_length=64, verbose_name='main_actor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movie',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(default='', max_length=16, verbose_name='movie_id')),
                ('genre_id', models.CharField(default='', max_length=16, verbose_name='genre_id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Movie_Genre',
                'verbose_name_plural': 'Movie_Genre',
                'db_table': 'movie_genre',
                'unique_together': {('movie_id', 'genre_id')},
            },
        ),
    ]
