# Generated by Django 3.1.7 on 2021-04-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie_genre',
            unique_together=set(),
        ),
    ]
