# Generated by Django 3.1.7 on 2021-04-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=16, verbose_name='title')),
                ('plot', models.CharField(max_length=512, verbose_name='plot')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('date', models.CharField(max_length=16, verbose_name='date')),
                ('rating', models.CharField(default='', max_length=8, verbose_name='rating')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='register_time')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='modify_time')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
                'db_table': 'test',
            },
        ),
    ]
